backend:
  name: github
  repo: thehejjoking/my-blog
  branch: main
  auth_scope: repo
  base_url: https://api.github.com
  client_id: Ov23lizz4TxjTdzPOmMk
  client_secret: bedc3f404f0f3ef2b326b6f7160916eb065f10e0

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/pages/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
