backend:
  name: github
  repo: thehejjoking/my-blog
  branch: main
  base_url: https://decap-proxy.aaron-senese2010.workers.dev
  auth_endpoint: auth
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }